apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: pgbhz/kub-demo-frontend:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"